server:
  port: 8888
spring:
#  profiles:
#    active: native
  cloud:
    config:
      server:
#        native:
#          searchLocations: file:///Users/zhailiang/Documents/pinzhi365/workspace/git-hub/microservice/ms-config/servicex,file:///Users/zhailiang/Documents/pinzhi365/workspace/git-hub/microservice/ms-config/servicey
        git:
          uri: https://github.com/jojozhai/microservice
          searchPaths: 'ms-config/{application}'
          username: zhailiang@pinzhi365.com
          password: Zhai800223