spring:
  application:
    name: servicex
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8888/

server:
  port: 7777

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
y:
  test:
    value:
      1: hehe
      2: aaaa
