spring:
  application:
    name: servicey
  profiles:
    active: default
  cloud:
    config:
      uri: http://localhost:8888/
      
server:
  port: 6666
      
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      